name: Deploy Angular to Cloud Run DEV

on:
  push:
    branches:
      - develop
  workflow_dispatch:     # 👈 Añade esta línea para habilitar el botón manual

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    # 👇 Asociamos el entorno GitHub según la rama
    environment: 'dev'

    env:
      NG_APP_BACKEND_URL: ${{ vars.BACKEND_URL }}
      NG_APP_IMGPATH: ${{ vars.IMGPATH }}
      NG_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      NG_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      NG_APP_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: europe-west1
      SERVICE_NAME: seriesapp-frontend-dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 👈 Clona todo el historial (necesario para GitVersion)

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3
        with:
          versionSpec: '5.x'

      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3

      - name: Show calculated version
        run: echo "Version = ${{ steps.gitversion.outputs.SemVer }}"

      # 👇 Este paso genera environment.ts con la versión incluida
      - name: Generate environment file
        run: node scripts/set-env.cjs "${{ steps.gitversion.outputs.SemVer }}"

      - name: Build Angular app
        run: npm run build --configuration='development'

      # --- Autenticación ---
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      # --- Construcción de la imagen ---
      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/frontend/${{ env.SERVICE_NAME }}:latest .

      - name: Push Docker image
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/frontend/${{ env.SERVICE_NAME }}:latest

      # --- Despliegue en Cloud Run ---
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/frontend/${{ env.SERVICE_NAME }}:latest \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated
