name: Build and Release

on:
#  push:
#    branches:
#      - master
  workflow_dispatch: # Ejecución manual

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    # 👇 Asociamos el entorno GitHub según la rama
    environment: ${{ github.ref_name == 'master' && 'prod' || 'dev' }}

    env:
      NG_APP_BACKEND_URL: ${{ vars.BACKEND_URL }}
      NG_APP_IMGPATH: ${{ vars.IMGPATH }}
      NG_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      NG_APP_FIREBASE_AUTH_DOMAIN: ${{ vars.FIREBASE_AUTH_DOMAIN }}
      NG_APP_FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      GCP_REGION: ${{ vars.GCP_REGION }}
      GCP_ARTIFACT_REPOSITORY: ${{ vars.GCP_ARTIFACT_REPOSITORY }}
      GCP_PROJECT: ${{ vars.GCP_PROJECT }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ vars.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 👈 Clona todo el historial (necesario para GitVersion)

      - name: Determine build type
        run: |
          if [ "${{ github.ref_name }}" = "master" ]; then
            echo "BUILD_TYPE=release" >> $GITHUB_ENV
          else
            echo "BUILD_TYPE=debug" >> $GITHUB_ENV
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3
        with:
          versionSpec: '5.x'

      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3

      - name: Show calculated version
        run: |
          echo "VERSION_NAME=${{ steps.gitversion.outputs.SemVer }}" >> $GITHUB_ENV
          echo "VERSION_CODE=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build Angular app
        run: npm run build -- --configuration production

      - name: Package build artifact
        run: |
          cd www
          zip -r ../app-dist.zip .
        shell: bash

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-dist
          path: app-dist.zip

      # --- Generar changelog automático ---
      - name: Generate changelog
        id: changelog
        run: |
          # Encuentra el último tag
          LAST_TAG=$(git describe --tags --abbrev=0 || echo "")
          echo "Last tag: $LAST_TAG"
          if [ -z "$LAST_TAG" ]; then
          # Si no hay tag, listamos todos los commits
          CHANGELOG=$(git log --pretty=format:"- %s (%h)")
          else
          CHANGELOG=$(git log $LAST_TAG..HEAD --pretty=format:"- %s (%h)")
          fi
          echo "$CHANGELOG" > changelog.txt
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          cat changelog.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # --- Instalar Java ---
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # --- Instalar Android SDK ---
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 👇 Este paso genera environment.ts con la versión incluida
      - name: Generate environment file
        run: node scripts/set-env.cjs "${{ steps.gitversion.outputs.SemVer }}"

      - name: Build Angular app with conf
        run: npm run build --configuration='production'

      # --- Add Capacitor ---
      - name: Capacitor add (Android)
        run: npx cap add android

      # --- Modify variables.gradle ---
      - name: Modify android/variables.gradle for Firebase
        run: |
          echo "Modifying android/variables.gradle to set minSdkVersion to 23"
          sed -i "s/minSdkVersion = [0-9]*/minSdkVersion = 23/" android/variables.gradle
          echo "✅ File content after modification:"
          cat android/variables.gradle

      # --- Add Firebase dependencies ---
      - name: Add Firebase dependencies to android/app/build.gradle
        run: |
          echo "Adding Firebase dependencies to android/app/build.gradle"
          # Añadimos las dependencias al final del bloque 'dependencies'
          sed -i "/dependencies {/a \    implementation platform('com.google.firebase:firebase-bom:33.1.2')\n    implementation 'com.google.firebase:firebase-auth'\n    implementation 'com.google.android.gms:play-services-auth'\n    implementation project(':capacitor-firebase-authentication')" android/app/build.gradle
          echo "✅ File content after modification:"
          cat android/app/build.gradle

      # --- Configure Android signing (release) ---
      - name: Configure Android signing in build.gradle
        if: env.BUILD_TYPE == 'release'
        run: |
          FILE=android/app/build.gradle
          
          echo "🔧 Configuring signingConfigs in $FILE"
          
          # Añadir signingConfigs dentro de android {}
          sed -i '/android {/a\
              signingConfigs {\
                  release {\
                      storeFile file("seriesapp.keystore")\
                      storePassword System.getenv("ANDROID_KEYSTORE_PASSWORD")\
                      keyAlias System.getenv("ANDROID_KEY_ALIAS")\
                      keyPassword System.getenv("ANDROID_KEY_PASSWORD")\
                  }\
              }\
          ' $FILE
          
          # Añadir buildTypes.release si no existe
          sed -i '/buildTypes {/a\
                  release {\
                      signingConfig signingConfigs.release\
                  }\
          ' $FILE
          
          echo "✅ build.gradle after signing config:"
          cat $FILE

      # --- Add Capacitor ---
      - name: Add deep link to AndroidManifest.xml
        run: |
          MANIFEST=android/app/src/main/AndroidManifest.xml          
          sed -i '/<\/activity>/i\
                      <intent-filter>\
                          <action android:name="android.intent.action.VIEW" />\
                          <category android:name="android.intent.category.DEFAULT" />\
                          <category android:name="android.intent.category.BROWSABLE" />\
                          <data android:scheme="es.meco.seriesapp" android:host="firebaseauth" />\
                      </intent-filter>' "$MANIFEST"
          cat android/app/src/main/AndroidManifest.xml

      # --- Generate google-services.json ---
      - name: Generate google-services.json
        run: |
          cat <<'EOF' > android/app/google-services.json
          ${{ secrets.GOOGLE_SERVICES_JSON }}
          EOF
          echo "Verify google-services.json file generated"
          ls -l android/app/google-services.json

      # --- Decode keystore ---
      - name: Decode keystore
        if: env.BUILD_TYPE == 'release'
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/app/seriesapp.keystore

      # --- Generate App Icons ---
      - name: Generate App Icons
        run: |
          # Asegurarse de que la carpeta assets existe y tiene el icono
          mkdir -p assets
          cp src/assets/seriesapp-logo.png assets/icon.png
          cp src/assets/seriesapp-logo.png assets/splash.png
                 
          # Generar iconos forzando Android
          npx capacitor-assets generate --android --iconBackgroundColor '#141414' --iconBackgroundColorDark '#141414'

      # --- Build APK RELEASE ---
      - name: Build APK
        run: |
          chmod +x android/gradlew
          cd android
          
          if [ "${BUILD_TYPE}" = "release" ]; then
            ./gradlew assembleRelease \
              -PversionName=${{ env.VERSION_NAME }} \
              -PversionCode=${{ env.VERSION_CODE }}
          else
            ./gradlew assembleDebug \
              -PversionName=${{ env.VERSION_NAME }} \
              -PversionCode=${{ env.VERSION_CODE }}
          fi

      # --- Verify debug APK certificate ---
      - name: Verify debug APK/Keystore certificate
        if: env.BUILD_TYPE == 'debug'
        run: |
          echo 'SHA-1 of app-debug.apk'
          keytool -printcert -jarfile android/app/build/outputs/apk/debug/app-debug.apk

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.gitversion.outputs.SemVer }}
          name: "Release v${{ steps.gitversion.outputs.SemVer }}"
          body: |
            ## Changelog

            ${{ env.CHANGELOG }}

            Version Name: ${{ env.VERSION_NAME }}
            Version Code: ${{ env.VERSION_CODE }}
          files: |
            app-dist.zip
            android/app/build/outputs/apk/${{ env.BUILD_TYPE }}/app-${{ env.BUILD_TYPE }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
